# Generated by Django 4.2.6 on 2023-12-28 09:16

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=100)),
                ('link_url', models.URLField()),
                ('link_image', models.ImageField(upload_to='links_images')),
            ],
            options={
                'verbose_name_plural': 'Links',
            },
        ),
        migrations.CreateModel(
            name='SkillsOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('option', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='portfolio.skillsoption')),
            ],
            options={
                'verbose_name_plural': 'Skills',
            },
        ),
    ]
