# Generated by Django 4.2.6 on 2023-12-28 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.skillsoption'),
        ),
    ]
