# Generated by Django 4.2.6 on 2023-12-28 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_skills_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='option',
            new_name='skills_opt',
        ),
    ]
