# Generated by Django 4.2.6 on 2023-12-28 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_option_skills_skills_opt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
