# Generated by Django 4.2.6 on 2023-12-28 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_delete_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skills_opt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.skillsoption')),
            ],
            options={
                'verbose_name_plural': 'Skills',
            },
        ),
    ]
