# Generated by Django 4.2.6 on 2023-12-28 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_devskills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devskills',
            old_name='skills_opt',
            new_name='option',
        ),
    ]
