# Generated by Django 4.2.6 on 2023-12-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AlterField(
            model_name='skills',
            name='option',
            field=models.CharField(choices=[('OtherSkills', 'OtherSkills'), ('Front-End Development', 'Front-End Development'), ('Back-End Development', 'Back-End Development')], max_length=100),
        ),
    ]
