# Generated by Django 4.2.6 on 2023-12-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_remove_profile_role_alter_skills_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobroles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='skills',
            name='option',
            field=models.CharField(choices=[('Back-End Development', 'Back-End Development'), ('Front-End Development', 'Front-End Development'), ('OtherSkills', 'OtherSkills')], max_length=100),
        ),
    ]
