# Generated by Django 4.2.6 on 2023-12-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_jobroles_alter_skills_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Project_pic')),
                ('title', models.CharField(max_length=200)),
                ('languages_used', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='skills',
            name='option',
            field=models.CharField(choices=[('OtherSkills', 'OtherSkills'), ('Back-End Development', 'Back-End Development'), ('Front-End Development', 'Front-End Development')], max_length=100),
        ),
    ]
