# Generated by Django 4.2.6 on 2023-12-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_alter_projects_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume_doc',
            field=models.FileField(blank=True, null=True, upload_to='resume_doc'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='option',
            field=models.CharField(choices=[('OtherSkills', 'OtherSkills'), ('Front-End Development', 'Front-End Development'), ('Back-End Development', 'Back-End Development')], max_length=100),
        ),
    ]
