# Generated by Django 4.2.6 on 2023-12-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_profile_resume_doc_alter_skills_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='photo',
            field=models.ImageField(upload_to='project_picture_path'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='option',
            field=models.CharField(choices=[('Back-End Development', 'Back-End Development'), ('OtherSkills', 'OtherSkills'), ('Front-End Development', 'Front-End Development')], max_length=100),
        ),
    ]
