# Generated by Django 4.2.6 on 2023-12-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_alter_projects_photo_alter_skills_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(upload_to='profile_pic,resume_doc'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume_doc',
            field=models.FileField(blank=True, null=True, upload_to='profile_pic,resume_doc'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='photo',
            field=models.ImageField(upload_to='project_pic'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='option',
            field=models.CharField(choices=[('OtherSkills', 'OtherSkills'), ('Back-End Development', 'Back-End Development'), ('Front-End Development', 'Front-End Development')], max_length=100),
        ),
    ]
