# Generated by Django 4.2.6 on 2023-12-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_alter_profile_photo_alter_profile_resume_doc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='description1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='description2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='description3',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='project_pic'),
        ),
        migrations.AddField(
            model_name='projects',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='project_pic'),
        ),
        migrations.AddField(
            model_name='projects',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='project_pic'),
        ),
        migrations.AddField(
            model_name='projects',
            name='title1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='title2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='title3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='option',
            field=models.CharField(choices=[('Back-End Development', 'Back-End Development'), ('OtherSkills', 'OtherSkills'), ('Front-End Development', 'Front-End Development')], max_length=100),
        ),
    ]
