# Generated by Django 4.2.6 on 2023-12-31 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_projects_technology_used_alter_skills_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='option',
            field=models.CharField(choices=[('OtherSkills', 'OtherSkills'), ('Back-End Development', 'Back-End Development'), ('Front-End Development', 'Front-End Development')], max_length=100),
        ),
    ]
