# Generated by Django 4.2.6 on 2023-12-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_profile_about_alter_skills_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='option',
            field=models.CharField(choices=[('Front-End Development', 'Front-End Development'), ('OtherSkills', 'OtherSkills'), ('Back-End Development', 'Back-End Development')], max_length=100),
        ),
    ]
