# Generated by Django 4.2.6 on 2023-12-31 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_alter_skills_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='description4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='option',
            field=models.CharField(choices=[('Back-End Development', 'Back-End Development'), ('OtherSkills', 'OtherSkills'), ('Front-End Development', 'Front-End Development')], max_length=100),
        ),
    ]
